"""ALL CONSTANTS FOR GAME"""

LIVES = 5

WARRIOR = 1
ROBBER = 2
WIZARD = 3

ALLOWED_ATTACKS = [1, 2, 3]

exodus_1 = {WARRIOR - ROBBER, ROBBER - WIZARD, WIZARD - WARRIOR}
exodus_2 = {WARRIOR - WIZARD, ROBBER - WARRIOR, WIZARD - ROBBER}
